### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anikajoe** [anuragrana/Python-Scripts#2]
ImportError                               Traceback (most recent call last)
<ipython-input-1-9ba2789a13b3> in <module>
      2 import requests
      3 import telegram
----> 4 from config import telegram_token_news
      5 

ImportError: cannot import name 'telegram_token_news'

**Comment by anuragrana** [comment]
You need to create a separate file with name config.py and store telegram token into it and then import that token in this file.

**Comment by rahult07** [comment]
python tweets_scrapper.py narendramodi


Downloading tweets for narendramodi
Traceback (most recent call last):
  File "tweets_scrapper.py", line 131, in <module>
    start()
  File "tweets_scrapper.py", line 125, in start
    tweets = get_tweets_data(username, soup)
  File "tweets_scrapper.py", line 52, in get_tweets_data
    next_pointer = soup.find("div", {"class": "stream-container"})["data-min-position"]
TypeError: 'NoneType' object is not subscriptable
